import Link from "next/link";

export function SiteHeader() {
  return <>
    <div className="topbar"><span>Black-owned • Licensed & insured • 15-minute response target</span><a href="tel:+12167033183">Emergency service available: 216-703-3183 <b>→</b></a></div>
    <header className="header">
      <Link className="logo-crop" href="/" aria-label="Eternity Mechanical Services home"><img src="/images/eternity-logo.svg" alt="Eternity Mechanical Services" /></Link>
      <nav aria-label="Primary navigation"><Link href="/services/air-conditioning-repair">Cooling</Link><Link href="/services/furnace-heating-repair">Heating</Link><Link href="/services/commercial-hvac">Commercial HVAC</Link><Link href="/services/commercial-refrigeration">Refrigeration</Link><Link href="/services/preventive-maintenance">Maintenance</Link><Link href="/projects">Projects</Link><Link href="/resources">Expert answers</Link><Link href="/areas-we-serve">Areas served</Link><Link href="/#about">About</Link><Link href="/#contact">Contact</Link></nav>
      <div className="header-actions"><a className="btn btn-small" href="https://eternityhvacr.com/#schedule">Request service</a></div>
      <details className="mobile-menu"><summary aria-label="Open navigation"><span /><span /><span /></summary><div><Link href="/services/air-conditioning-repair">AC repair</Link><Link href="/services/air-conditioning-installation">AC installation</Link><Link href="/services/furnace-heating-repair">Heating</Link><Link href="/services/boiler-service">Boilers</Link><Link href="/services/heat-pump-service">Heat pumps</Link><Link href="/services/emergency-hvac-r">Emergency HVAC/R</Link><Link href="/services/commercial-hvac">Commercial HVAC</Link><Link href="/services/commercial-refrigeration">Refrigeration</Link><Link href="/services/preventive-maintenance">Maintenance</Link><Link href="/projects">Projects</Link><Link href="/resources">Expert answers</Link><Link href="/areas-we-serve">Areas served</Link><Link href="/#contact">Contact</Link></div></details>
    </header>
  </>;
}

export function SiteFooter() {
  return <>
    <footer><div className="footer-grid"><div className="footer-brand"><div className="logo-crop footer-logo"><img src="/images/eternity-logo-reverse.svg" alt="Eternity Mechanical Services" /></div><p>Licensed and insured HVAC, refrigeration, installation, repair and preventive maintenance for residential and commercial customers.</p></div><div><h3>Services</h3><Link href="/services/air-conditioning-repair">AC repair</Link><Link href="/services/air-conditioning-installation">AC installation & replacement</Link><Link href="/services/furnace-heating-repair">Furnace & heating</Link><Link href="/services/boiler-service">Boiler service</Link><Link href="/services/heat-pump-service">Heat pumps</Link><Link href="/services/emergency-hvac-r">Emergency HVAC/R</Link><Link href="/services/commercial-hvac">Commercial HVAC</Link><Link href="/services/commercial-refrigeration">Commercial refrigeration</Link><Link href="/services/preventive-maintenance">Preventive maintenance</Link></div><div><h3>Company</h3><Link href="/#about">About</Link><Link href="/projects">Project case studies</Link><Link href="/resources">Expert answers</Link><a href="https://share.google/1bUl6S4x9x90TJ7Mf" target="_blank" rel="noreferrer">Google profile</a><a data-review-link href="https://g.page/r/CYsWl6Bz9AJvEBM/review" target="_blank" rel="noreferrer">Write a Google review</a><Link href="/areas-we-serve">Areas we serve</Link><Link href="/areas-we-serve/euclid-oh">Euclid HVAC service</Link><Link href="/#contact">Contact</Link></div><div><h3>Customer</h3><a href="https://eternityhvacr.com/#schedule">Request service</a><a href="https://eternityhvacr.com/#schedule">Request estimate</a><a data-sms-link href="sms:+12167033183">Text Eternity</a><Link href="/services/commercial-hvac">Commercial service</Link><Link href="/services/preventive-maintenance">Maintenance</Link><Link href="/privacy">Privacy & data use</Link><Link href="/terms">Website terms</Link></div><div><h3>Contact</h3><p>Cleveland, Cuyahoga County<br />Greater Cleveland & Northeast Ohio</p><a href="tel:+12167033183">Call 216-703-3183</a><a data-sms-link href="sms:+12167033183">Text 216-703-3183</a><a href="mailto:ben@eternityhvacr.com">ben@eternityhvacr.com</a><span>Mon–Fri: 7 a.m.–7 p.m.</span><span>Sat: 9 a.m.–5 p.m. • Sun: Closed</span></div></div><p className="sms-disclosure">Texts are monitored 24/7 with a 15-minute reply target. This is not an arrival-time promise. By texting, you agree to receive service-related replies at the number you use. Message and data rates may apply. Reply STOP to opt out. No marketing texts without separate consent. See our <Link href="/privacy">Privacy & Data Use notice</Link>.</p><div className="footer-bottom"><span>© 2026 Eternity Mechanical Services LLC. All rights reserved.</span><span><Link href="/privacy">Privacy</Link> • <Link href="/terms">Terms</Link></span><span>Licensed & insured • License #28303</span><span>Service-area business • Greater Cleveland</span></div></footer>
    <nav className="mobile-bar" aria-label="Quick contact actions">
      <a href="tel:+12167033183"><span aria-hidden="true">☎</span>Call</a>
      <a href="https://eternityhvacr.com/#schedule"><span aria-hidden="true">＋</span>Request</a>
      <a data-sms-link href="sms:+12167033183"><span aria-hidden="true">✉</span>Text</a>
    </nav>
  </>;
}
